# Generated by Django 3.2.9 on 2021-12-12 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='edition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.edition'),
        ),
    ]
