# Generated by Django 3.2.9 on 2021-12-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20211212_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/edition/'),
        ),
    ]
